name: build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  plugin_matrix:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact-suffix: linux-x86-64
            libfaust-zip: https://github.com/grame-cncm/faust/releases/download/2.83.1/libfaust-ubuntu-x86_64.zip
          - os: macos-latest
            artifact-suffix: macos-arm64
            libfaust-dmg: https://github.com/grame-cncm/faust/releases/download/2.83.1/Faust-2.83.1-arm64.dmg
            brew-dependencies: faust
          - os: macos-15-intel
            artifact-suffix: macos-x86-64
            libfaust-dmg: https://github.com/grame-cncm/faust/releases/download/2.83.1/Faust-2.83.1-x64.dmg
          - os: windows-2022
            artifact-suffix: win-x86-64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Checkout SuperCollider
      uses: actions/checkout@v4
      with:
        repository: "supercollider/supercollider"
        ref: "main"
        path: "supercollider"
    - name: Download faust zip
      if: ${{ matrix.libfaust-zip }}
      run: |
        wget -q -O libfaust.zip ${{ matrix.libfaust-zip }} 
        mkdir libfaust
        unzip libfaust.zip -d libfaust/
    - name: Download faust dmg
      if: ${{ matrix.libfaust-dmg }}
      run: |
        brew install sevenzip
        wget -q -O libfaust.dmg ${{ matrix.libfaust-dmg }}
        7zz x libfaust.dmg -o./libfaustraw || true
        mkdir libfaust
        mv libfaustraw/Faust-*/Faust-*/lib libfaust/lib
    - name: Install faust (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install faust -y
        mkdir libfaust
        cp -r "C:/Program Files/Faust/lib" libfaust/lib
      shell: bash
    - name: Build Plugin
      shell: bash
      run: |
        cmake \
            -S . \
            -B build \
            -DSC_PATH=./supercollider \
            -DFAUST_LIB_DIR=./libfaust \
            -DSC_INSTALL_DIR=./install
        cmake --build build --config Release
        cmake --install build --config Release
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sc_faust-${{  matrix.artifact-suffix }}
        path: install/
